import type { InvitationData } from "@/types/invitation";

export const invitationData: InvitationData = {
  couple: {
    groom: "",
    bride: "",
    groomFull: "",
    brideFull: "",
    groomParents: "",
    brideParents: "",
  },
  event: {
    events: [
      {
        name: "",
        date: "",
        day: "",
        lunarDate: "",
        time: "",
        venue: "",
        address: "",
        city: "",
        mapsUrl: "",
        mapsLabel: "",
        mapsEnabled: true,
      },
      {
        name: "Resepsi",
        date: "",
        day: "",
        lunarDate: "",
        time: "10:00 - 12:00",
        venue: "",
        address: "",
        city: "",
        mapsUrl: "",
        mapsLabel: "",
        mapsEnabled: true,
      },
    ],
  },
  gift: {
    sectionLabel: "",
    title: "",
    description: "",
    bankName: "",
    accountHolder: "",
    accountNumber: "",
    ewalletName: "",
    ewalletHolder: "",
    ewalletNumber: "",
    address: "",
    thankYou: "",
    closingArabic: "",
    accounts: [],
  },
  story: [],
  gallery: [],
  music: { src: "", autoplay: false },
  theme: { mode: "system" },
  hashtag: "",
  themeColor: "",
  header: {
    label: "",
    groomName: "",
    brideName: "",
    dateText: "",
    locationText: "",
    hashtag: "",
    prayerTitle: "",
    prayerArabic: "",
    prayerTranslation: "",
    footerLabel: "",
    footerShareText: "",
    footerShareEnabled: true,
    footerHonorText: "",
    footerMadeWithText: "",
    footerCopyright: "",
  },
  opening: {
    images: [],
    interval: 4500,
    enabled: true,
  },
};
