import type { InvitationData } from "@/types/invitation";

export const invitationData: InvitationData = {
  couple: {
    groom: "",
    bride: "",
    groomFull: "",
    brideFull: "",
    groomParents: "",
    brideParents: "",
  },
  event: {
    akad: {
      name: "",
      date: "",
      day: "",
      lunarDate: "",
      time: "",
      venue: "",
      address: "",
      city: "",
      mapsUrl: "",
      mapsLabel: "",
    },
    reception: {
      name: "",
      date: "",
      day: "",
      lunarDate: "",
      time: "",
      venue: "",
      address: "",
      city: "",
      mapsUrl: "",
      mapsLabel: "",
    },
  },
  gift: {
    sectionLabel: "",
    title: "",
    description: "",
    bankName: "",
    accountHolder: "",
    accountNumber: "",
    ewalletName: "",
    ewalletHolder: "",
    ewalletNumber: "",
    address: "",
    thankYou: "",
    closingArabic: "",
    accounts: [],
  },
  story: [],
  gallery: [],
  music: { src: "", autoplay: false },
  theme: { mode: "system" },
  hashtag: "",
  themeColor: "",
  header: {
    label: "",
    groomName: "",
    brideName: "",
    dateText: "",
    locationText: "",
    hashtag: "",
    prayerTitle: "",
    prayerArabic: "",
    prayerTranslation: "",
    footerLabel: "",
    footerShareText: "",
    footerHonorText: "",
    footerMadeWithText: "",
    footerCopyright: "",
  },
};
